language: objective-c
osx_image: xcode8.1
xcode_project: Fridge.xcodeproj
xcode_scheme: Fridge
xcode_sdk: macosx10.12

# safelist
branches:
  only:
  - master

after_success:
bash <(curl -s https://codecov.io/bash)
