language: swift
osx_image: xcode11.3
xcode_project: Fridge.xcodeproj

# put back to only: - master later
branches:
##  only:
  - development
  - swift5

script:
- set -o pipefail
- swift build

after_success:
##upload coverage data to codecov
- bash <(curl -s https://codecov.io/bash)
