language: swift
osx_image: xcode11.3
xcode_project: Fridge.xcodeproj

# put back to only: - master later
branches:
  - master
  - development

script:
- set -o pipefail
- swift build

# Add back later
# after_success:
##upload coverage data to codecov
# - bash <(curl -s https://codecov.io/bash)
