language: swift #objective-c
osx_image: xcode8.2
xcode_project: Fridge.xcodeproj
xcode_scheme: Fridge
xcode_sdk: macosx10.12

# put back to only: - master later
branches:
##  only:
  - master
  - development
  - travis_jurney

before_install:
  - brew update

script:
- xcodebuild clean build -project Fridge.xcodeproj -scheme Fridge
- xcodebuild build test -project Fridge.xcodeproj -scheme Fridge -sdk macosx -configuration Debug -enableCodeCoverage YES ENABLE_TESTABILITY=YES

after_success:
##upload coverage data to codecov
- bash <(curl -s https://codecov.io/bash)

after_failure:
## check what's available and how
- xcodebuild -project Fridge.xcodeproj -scheme Fridge -list
- xcodebuild -project Fridge.xcodeproj -scheme Fridge -showBuildSettings
