language: objective-c
osx_image: xcode8
xcode_project: Fridge.xcodeproj
xcode_scheme: Fridge
xcode_sdk: macosx10.12

# safelist
branches:
  only:
  - master
  
script:
- xcodebuild clean build -project Fridge.xcodeproj -scheme Fridge

after_success:
## we're trying to Test if build passes
- xcodebuild -project Fridge.xcodeproj -scheme Fridge -showBuildSettings
- xcodebuild test -project Fridge.xcodeproj -scheme Fridge -destination 'platform=OS X, arch=x86_64'
- bash <(curl -s https://codecov.io/bash)
