# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Basic build

on:
  push:
    branches: [ main, development ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Commandline basic build
      run: swift build -v
    - name: Tests collection
      run: swift test -v
