name: Fridge Mac build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  tests-macos:
    runs-on: macos-latest
    name: macOS Simulators

    steps:
    - uses: actions/checkout@v2
    - name: Mac x86_64
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64"
    - name: Mac Catalyst
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64,variant=Mac Catalyst"

# NOTE: Add DriverKit later
# - name: DriverKit
#   run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64,variant=DriverKit"
