name: Fridge macOS tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    name: Fridge warmup build

    steps:
    - uses: actions/checkout@v2
    - name: Pure swift build
      run: swift build -v

  tests-macos:
    runs-on: macos-latest
    name: Destination -> macOS

    steps:
    - uses: actions/checkout@v2
    - name: Mac x86_64
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64"
    - name: Mac Catalyst
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64,variant=Mac Catalyst"
    # - name: DriverKit
    #   run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64,variant=DriverKit"
