name: Fridge release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    name: Swift and xcodebuild variations for building Fridge library
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Swift build
      run: swift build -v
    - name: xcodebuild build
      run: xcodebuild build-for-testing -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 8"
    - name: xcodebuild build
      run: xcodebuild build-for-testing -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 11"
    - name: xcodebuild build
      run: xcodebuild build-for-testing -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 12"
    - name: xcodebuild iOS testing
      run: xcodebuild test-without-building -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 8"
#    - name: xcodebuild tvOS testing
#      run: xcodebuild test-without-building -scheme Fridge -destination "platform=tvOS Simulator,name=Apple TV 4K (at 1080p) (2nd generation)
#    - name: xcodebuild watchOS
#      run: xcodebuild build-for-testing -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 8"
