name: Fridge release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    name: Release build

    steps:
    - uses: actions/checkout@v2
    - name: Swift build
      run: swift build -v
    - name: iPhone 8
      run: xcodebuild build-for-testing -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 8"
    - name: iPhone 11
      run: xcodebuild build-for-testing -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 11"
    - name: iPhone 12
      run: xcodebuild build-for-testing -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 12"
