name: Fridge test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    name: Fridge warmup build

    steps:
    - uses: actions/checkout@v2
    - name: Pure swift build
      run: swift build -v

  tests-ios:
    runs-on: macos-latest
    name: Destination -> iOS

    steps:
    - uses: actions/checkout@v2
    - name: iPhone 8
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 8"
    - name: iPhone 11
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 11"
    - name: iPhone 11 Pro
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 11 Pro"
    - name: iPhone 11 Pro Max
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max"
    - name: iPhone 12
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 12"
    - name: iPhone 12 Pro
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 12 Pro"
    - name: iPhone 12 Pro Max
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 12 Pro Max"
    - name: iPad (9th generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad (9th generation)"
    - name: iPad (10th generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad (10th generation)"
    - name: iPad Air (4th generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad Air (4th generation)"
    - name: iPad Air (5th generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad Air (5th generation)"
    - name: iPad Pro (9.7-inch)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad Pro (9.7-inch)"
    - name: iPad Pro (11-inch) (3rd generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad Pro (11-inch) (3rd generation)"
    - name: iPad Pro (11-inch) (4th generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad Pro (11-inch) (4th generation)"
    - name: iPad Pro (12.9-inch) (4th generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (5th generation)"
    - name: iPad Pro (12.9-inch) (5th generation)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation)"

  tests-macos:
    runs-on: macos-latest
    name: Destination -> macOS

    steps:
    - uses: actions/checkout@v2
    - name: Mac x86_64
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64"
    - name: Mac Catalyst
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64,variant=Mac Catalyst"
    - name: DriverKit
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=macOS,arch=x86_64,variant=DriverKit"

  tests-watchos:
    runs-on: macos-latest
    name: Destination -> watchOS

    steps:
    - uses: actions/checkout@v2
    - name: Apple Watch Series 5 - 40mm
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=watchOS Simulator,name=Apple Watch Series 5 - 40mm"
    - name: Apple Watch Series 5 - 44mm
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm"
    - name: Apple Watch Series 6 - 40mm
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 40mm"
    - name: Apple Watch Series 6 - 44mm
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm"
    - name: Apple Watch Series 7 - 41mm
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=watchOS Simulator,name=Apple Watch Series 7 - 41mm"
    - name: Apple Watch Series 7 - 45mm
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=watchOS Simulator,name=Apple Watch Series 7 - 45mm"

  tests-tvos:
    runs-on: macos-latest
    name: Destination -> tvOS

    steps:
    - uses: actions/checkout@v2
    - name: Apple TV
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=tvOS Simulator,name=Apple TV"
    - name: Apple TV 4k
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=tvOS Simulator,name=Apple TV 4k (2nd generation)"
    - name: Apple TV 4k (at 1080p)
      run: xcodebuild clean test -scheme "Fridge" -destination "platform=tvOS Simulator,name=Apple TV 4k (at 1080p) (2nd generation)"
