name: Fridge tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    name: Fridge library testing suite

    steps:
    - uses: actions/checkout@v2
    - name: pure swift build
      run: swift build -v
    - name: Test - iOS Simulator 8
      run: xcodebuild test-without-building -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 8"
    - name: Test - iOS Simulator 11
      run: xcodebuild test-without-building -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 11"
    - name: Test - iOS Simulator 12
      run: xcodebuild test-without-building -scheme "Fridge" -destination "platform=iOS Simulator,name=iPhone 12"
